@EventDrivenOrderProcessor.SagaChoreography.Order.Api_HostAddress = http://localhost:5196

GET {{EventDrivenOrderProcessor.SagaChoreography.Order.Api_HostAddress}}/weatherforecast/
Accept: application/json

###
