@EventDrivenOrderProcessor.SagaOrchestration.Payment.Api_HostAddress = http://localhost:5200

GET {{EventDrivenOrderProcessor.SagaOrchestration.Payment.Api_HostAddress}}/weatherforecast/
Accept: application/json

###
